const Languages = {
    en: {
        CONTRACT_ADDRESS: "Contract Address",
        SPONSOR: "Sponsor",
        CHALLENGER: "Challenger",
        DETAIL: "Detail",
        PLACEHOLDER: "Search: Only Challenge Contract Address",
        SEARCH: "Search",
        DASHBOARD: "Dashboard",
        PREVIOUS: "Previous",
        PAGE: "Page",
        OF: "of",
        NEXT: "Next",
        ROLE: "Role",
        NAME: "Name",
        ADDRESS: "Address",
        QR_CODE: "Qa Code",
        CHALLENGE_INFORMATION: "Challenge Information",
        NETWORK: "Network",
        STATUS: "Status",
        CHALLENGE_START: "Challenge Start",
        CHALLENGE_END: "Challenge End",
        CHALLENGE_DAYS: "Challenge Days",
        MINIMUM_ACHIEVEMENT_DAYS: "Minimum Achievement Days",
        ACHIEVEMENT_RATIO: "Achievement Ratio",
        GIVE_UP: "Give Up",
        NFT: "NFT",
        STEP_DATA: "Step Data",
        DATE: "Date",
        STEPS: "Steps",
        DEPOSIT_COIN_ERC20: "Deposit(Coin/ERC-20)",
        INITIAL: "Initial",
        ADDITIONAL: "Additional",
        TOTAL: "Total",
        DIVIDEND_SUCCESS: "Dividend (Success)",
        PERCENTAGE: "Percentage",
        SYMBOL: "Symbol",
        DIVIDEND_FAILURE: "Dividend (Failure)",
        DEPOSIT_NFT: "Deposit(NFT)",
        COLLECTION: "Collection",
        TOKEN_ID: "Token ID",
        NONE: "None",
        NUMBER_OF_NFT: "Number of NFT",
        DESTINATION: "Destination",
        NOT_FINISH: "Not Finish",
        NOT_STARTED: "Not Started",
        FINISHED: "Finished",
        DAYS: "Days",
        YES: "Yes",
        NO: "No",
        AMOUNT: "Amount",
        CONFIRM_ERROR: "Yes, I sure and re-check",
        CLOSE_MODAL: "Close modal",
        INVALID_ETHEREUM_ADDRESS: "Invalid ethereum address",
        WRONG_NETWORK: "This address is not a contract or wrong network, Please check your network configuration",
        ALREADY_RESEARCH: "Already Research",
        NETWORK_NOT_FOUND: "Network not found",
        ENTER_ADDRESS: "Please enter a valid address",
        ERROR_NOT_FOUND: "Something went wrong, Please check your RPC configuration",
        LOADING: "Loading",
    },
    jp: {
        CONTRACT_ADDRESS: "契約名",
        SPONSOR: "スポンサー",
        CHALLENGER: "チャレンジャー",
        DETAIL: "詳細",
        PLACEHOLDER: "検索: 仮のチャレンジーコントラクトアドレス",
        SEARCH: "検索",
        DASHBOARD: "タブ",
        PREVIOUS: "前べ",
        PAGE: "ページ",
        OF: "の",
        NEXT: "次べ",
        ROLE: "ロール",
        NAME: "名前",
        ADDRESS: "アドレス",
        QR_CODE: "QR コード",
        CHALLENGE_INFORMATION: "チャレンジー情報",
        NETWORK: "ネットワーク",
        STATUS: "ステータス",
        CHALLENGE_START: "チャレンジー開始",
        CHALLENGE_END: "チャレンジー終了",
        CHALLENGE_DAYS: "チャレンジー日数",
        MINIMUM_ACHIEVEMENT_DAYS: "最低達成日数",
        ACHIEVEMENT_RATIO: "達成率",
        GIVE_UP: "放棄",
        NFT: "NFT",
        STEP_DATA: "ステップデータ",
        DATE: "日付",
        STEPS: "ステップ",
        DEPOSIT_COIN_ERC20: "入金(コイン/ERC-20)",
        INITIAL: "初期",
        ADDITIONAL: "追加",
        TOTAL: "合計",
        DIVIDEND_SUCCESS: "配当(成功)",
        PERCENTAGE: "割合",
        SYMBOL: "シンボ",
        DIVIDEND_FAILURE: "配当(失敗)",
        DEPOSIT_NFT: "入金(NFT)",
        COLLECTION: "コレクション",
        TOKEN_ID: "トークンID",
        NONE: "なし",
        NUMBER_OF_NFT: "NFTの数",
        DESTINATION: "宛先",
        NOT_FINISH: "未完了",
        NOT_STARTED: "未開始",
        FINISHED: "完了",
        DAYS: "日",
        YES: "はい",
        NO: "いいえ",
        AMOUNT: "金額",
        CONFIRM_ERROR: "はい、確認して確認",
        CLOSE_MODAL: "モデルを閉じる",
        INVALID_ETHEREUM_ADDRESS: "無効なEthereumアドレス",
        WRONG_NETWORK: "このアドレスはコントラクトまたは間違ったネットワークであることを確認してください",
        ALREADY_RESEARCH: "既に研究中",
        NETWORK_NOT_FOUND: "ネットワークが見つかりません",
        ENTER_ADDRESS: "有効なアドレスを入力してください",
        ERROR_NOT_FOUND: "何かがおかしいので、チェックしてください",
        LOADING: "読み込み中",
    }
};

export default Languages